% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Econ 573: Problem Set 1 - Part II},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Econ 573: Problem Set 1 - Part II}
\author{}
\date{\vspace{-2.5em}}

\begin{document}
\maketitle

Exercise 9

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{college }\OtherTok{=} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"C:/Users/mateo/OneDrive {-} University of North Carolina at Chapel Hill/Courses/Spring 2025/Econ 573/College.csv"}\NormalTok{) }\CommentTok{\#Read data into R}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{View}\NormalTok{(college)}
\CommentTok{\#view data}
\FunctionTok{rownames}\NormalTok{(college) }\OtherTok{\textless{}{-}}\NormalTok{ college[, }\DecValTok{1}\NormalTok{] }\CommentTok{\#creates a column with the names of each university recorded}
\FunctionTok{View}\NormalTok{(college)}
\NormalTok{college }\OtherTok{\textless{}{-}}\NormalTok{ college[, }\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{] }\CommentTok{\#eliminates first column}
\FunctionTok{View}\NormalTok{(college)}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
\end{enumerate}

i.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(college) }\CommentTok{\#produces a numerical summary of the variables in the data set}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Private               Apps           Accept          Enroll    
##  Length:777         Min.   :   81   Min.   :   72   Min.   :  35  
##  Class :character   1st Qu.:  776   1st Qu.:  604   1st Qu.: 242  
##  Mode  :character   Median : 1558   Median : 1110   Median : 434  
##                     Mean   : 3002   Mean   : 2019   Mean   : 780  
##                     3rd Qu.: 3624   3rd Qu.: 2424   3rd Qu.: 902  
##                     Max.   :48094   Max.   :26330   Max.   :6392  
##    Top10perc       Top25perc      F.Undergrad     P.Undergrad     
##  Min.   : 1.00   Min.   :  9.0   Min.   :  139   Min.   :    1.0  
##  1st Qu.:15.00   1st Qu.: 41.0   1st Qu.:  992   1st Qu.:   95.0  
##  Median :23.00   Median : 54.0   Median : 1707   Median :  353.0  
##  Mean   :27.56   Mean   : 55.8   Mean   : 3700   Mean   :  855.3  
##  3rd Qu.:35.00   3rd Qu.: 69.0   3rd Qu.: 4005   3rd Qu.:  967.0  
##  Max.   :96.00   Max.   :100.0   Max.   :31643   Max.   :21836.0  
##     Outstate       Room.Board       Books           Personal   
##  Min.   : 2340   Min.   :1780   Min.   :  96.0   Min.   : 250  
##  1st Qu.: 7320   1st Qu.:3597   1st Qu.: 470.0   1st Qu.: 850  
##  Median : 9990   Median :4200   Median : 500.0   Median :1200  
##  Mean   :10441   Mean   :4358   Mean   : 549.4   Mean   :1341  
##  3rd Qu.:12925   3rd Qu.:5050   3rd Qu.: 600.0   3rd Qu.:1700  
##  Max.   :21700   Max.   :8124   Max.   :2340.0   Max.   :6800  
##       PhD            Terminal       S.F.Ratio      perc.alumni   
##  Min.   :  8.00   Min.   : 24.0   Min.   : 2.50   Min.   : 0.00  
##  1st Qu.: 62.00   1st Qu.: 71.0   1st Qu.:11.50   1st Qu.:13.00  
##  Median : 75.00   Median : 82.0   Median :13.60   Median :21.00  
##  Mean   : 72.66   Mean   : 79.7   Mean   :14.09   Mean   :22.74  
##  3rd Qu.: 85.00   3rd Qu.: 92.0   3rd Qu.:16.50   3rd Qu.:31.00  
##  Max.   :103.00   Max.   :100.0   Max.   :39.80   Max.   :64.00  
##      Expend        Grad.Rate     
##  Min.   : 3186   Min.   : 10.00  
##  1st Qu.: 6751   1st Qu.: 53.00  
##  Median : 8377   Median : 65.00  
##  Mean   : 9660   Mean   : 65.46  
##  3rd Qu.:10830   3rd Qu.: 78.00  
##  Max.   :56233   Max.   :118.00
\end{verbatim}

ii.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{pairs}\NormalTok{(college[, }\DecValTok{2}\SpecialCharTok{:}\DecValTok{11}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\includegraphics{Econ473_ProblemSet1_PartII_files/figure-latex/unnamed-chunk-4-1.pdf}

iii.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{attach}\NormalTok{(college) }\CommentTok{\#makes variables from college available by name.}
\NormalTok{Private }\OtherTok{\textless{}{-}} \FunctionTok{as.factor}\NormalTok{(Private) }\CommentTok{\#the Private column will be treated as a categorical variable with two levels: "Yes and "No" }
\FunctionTok{plot}\NormalTok{(Outstate }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Private, }\CommentTok{\#Plots outsate as a function of Private}
     \AttributeTok{xlab =} \StringTok{"Private"}\NormalTok{,}
     \AttributeTok{ylab=} \StringTok{"Outstate"}\NormalTok{,}
     \AttributeTok{main =} \StringTok{"Boxplot of Outstate Tuition by Private/Public"}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\includegraphics{Econ473_ProblemSet1_PartII_files/figure-latex/unnamed-chunk-5-1.pdf}

iv.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Elite }\OtherTok{\textless{}{-}} \FunctionTok{rep}\NormalTok{(}\StringTok{"No"}\NormalTok{, }\FunctionTok{nrow}\NormalTok{(college)) }\CommentTok{\#creates a vector of the same length as the college data set with the value "No"}
\NormalTok{Elite[college}\SpecialCharTok{$}\NormalTok{Top10perc }\SpecialCharTok{\textgreater{}} \DecValTok{50}\NormalTok{] }\OtherTok{\textless{}{-}} \StringTok{"Yes"} \CommentTok{\#Check for rows where the percentage of top students is greater than 50\%. For those rows, the value in the Elite vectors is changed to "Yes"}
\NormalTok{Elite }\OtherTok{\textless{}{-}} \FunctionTok{as.factor}\NormalTok{(Elite)}
\NormalTok{college }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(college, Elite) }\CommentTok{\#converts vector into a factor, such that R will treate it as a categoricla grouping variable with two levels: "NO" and "Yes"}
\FunctionTok{summary}\NormalTok{(Elite)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  No Yes 
## 699  78
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{attach}\NormalTok{(college)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## The following objects are masked _by_ .GlobalEnv:
## 
##     Elite, Private
\end{verbatim}

\begin{verbatim}
## The following objects are masked from college (pos = 3):
## 
##     Accept, Apps, Books, Enroll, Expend, F.Undergrad, Grad.Rate,
##     Outstate, P.Undergrad, perc.alumni, Personal, PhD, Private,
##     Room.Board, S.F.Ratio, Terminal, Top10perc, Top25perc
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(Outstate }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Elite,}
     \AttributeTok{xlab =} \StringTok{"Oustate"}\NormalTok{,}
     \AttributeTok{ylab =} \StringTok{"Elite"}\NormalTok{,}
     \AttributeTok{main =} \StringTok{"Boxplot of Outstate Tuition by Elite"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Econ473_ProblemSet1_PartII_files/figure-latex/unnamed-chunk-6-1.pdf}

v.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow =} \FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{, }\DecValTok{2}\NormalTok{)) }\CommentTok{\#Divides the plotting area into 2x2 grid}
\FunctionTok{attach}\NormalTok{(college)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## The following objects are masked _by_ .GlobalEnv:
## 
##     Elite, Private
\end{verbatim}

\begin{verbatim}
## The following objects are masked from college (pos = 3):
## 
##     Accept, Apps, Books, Elite, Enroll, Expend, F.Undergrad, Grad.Rate,
##     Outstate, P.Undergrad, perc.alumni, Personal, PhD, Private,
##     Room.Board, S.F.Ratio, Terminal, Top10perc, Top25perc
\end{verbatim}

\begin{verbatim}
## The following objects are masked from college (pos = 4):
## 
##     Accept, Apps, Books, Enroll, Expend, F.Undergrad, Grad.Rate,
##     Outstate, P.Undergrad, perc.alumni, Personal, PhD, Private,
##     Room.Board, S.F.Ratio, Terminal, Top10perc, Top25perc
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{hist}\NormalTok{(Apps, }\AttributeTok{main =} \StringTok{"Histogram of Applications received"}\NormalTok{, }\AttributeTok{xlab =} \StringTok{"Applications received"}\NormalTok{, }\AttributeTok{breaks =} \DecValTok{20}\NormalTok{)}
\FunctionTok{hist}\NormalTok{(Enroll, }\AttributeTok{main =} \StringTok{"Histogram of New Enrollments"}\NormalTok{, }\AttributeTok{xlab =} \StringTok{"New Enrollments"}\NormalTok{, }\AttributeTok{breaks =} \DecValTok{30}\NormalTok{)}
\FunctionTok{hist}\NormalTok{(F.Undergrad, }\AttributeTok{main =} \StringTok{"Histogram of Full{-}time Undergraduates"}\NormalTok{, }\AttributeTok{xlab =} \StringTok{"Full{-}time Undergraduates"}\NormalTok{, }\AttributeTok{breaks =} \DecValTok{15}\NormalTok{)}
\FunctionTok{hist}\NormalTok{(Grad.Rate, }\AttributeTok{main =} \StringTok{"Histogram of Graduation Rate"}\NormalTok{, }\AttributeTok{xlab =} \StringTok{"Graduation Rate"}\NormalTok{, }\AttributeTok{breaks =} \DecValTok{25}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Econ473_ProblemSet1_PartII_files/figure-latex/unnamed-chunk-7-1.pdf}

vi. Continue exploring the data, and provide a brief summary of what you
discover

Exercise 9

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{auto }\OtherTok{=} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"C:/Users/mateo/OneDrive {-} University of North Carolina at Chapel Hill/Courses/Spring 2025/Econ 573/Auto.csv"}\NormalTok{)}
\FunctionTok{View}\NormalTok{(auto)}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(auto)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       mpg          cylinders      displacement    horsepower       
##  Min.   : 9.00   Min.   :3.000   Min.   : 68.0   Length:397        
##  1st Qu.:17.50   1st Qu.:4.000   1st Qu.:104.0   Class :character  
##  Median :23.00   Median :4.000   Median :146.0   Mode  :character  
##  Mean   :23.52   Mean   :5.458   Mean   :193.5                     
##  3rd Qu.:29.00   3rd Qu.:8.000   3rd Qu.:262.0                     
##  Max.   :46.60   Max.   :8.000   Max.   :455.0                     
##      weight      acceleration        year           origin     
##  Min.   :1613   Min.   : 8.00   Min.   :70.00   Min.   :1.000  
##  1st Qu.:2223   1st Qu.:13.80   1st Qu.:73.00   1st Qu.:1.000  
##  Median :2800   Median :15.50   Median :76.00   Median :1.000  
##  Mean   :2970   Mean   :15.56   Mean   :75.99   Mean   :1.574  
##  3rd Qu.:3609   3rd Qu.:17.10   3rd Qu.:79.00   3rd Qu.:2.000  
##  Max.   :5140   Max.   :24.80   Max.   :82.00   Max.   :3.000  
##      name          
##  Length:397        
##  Class :character  
##  Mode  :character  
##                    
##                    
## 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{str}\NormalTok{(auto)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    397 obs. of  9 variables:
##  $ mpg         : num  18 15 18 16 17 15 14 14 14 15 ...
##  $ cylinders   : int  8 8 8 8 8 8 8 8 8 8 ...
##  $ displacement: num  307 350 318 304 302 429 454 440 455 390 ...
##  $ horsepower  : chr  "130" "165" "150" "150" ...
##  $ weight      : int  3504 3693 3436 3433 3449 4341 4354 4312 4425 3850 ...
##  $ acceleration: num  12 11.5 11 12 10.5 10 9 8.5 10 8.5 ...
##  $ year        : int  70 70 70 70 70 70 70 70 70 70 ...
##  $ origin      : int  1 1 1 1 1 1 1 1 1 1 ...
##  $ name        : chr  "chevrolet chevelle malibu" "buick skylark 320" "plymouth satellite" "amc rebel sst" ...
\end{verbatim}

Based on the outputs we can conclude that ``miles per gallon'',
``cylinders'', ``displacement'', ``weight'', and ``acceleration'' are
all quantitative variables. While ``name'', ``horsepower'', ``year'',
and ``origin'' are qualitative variables.

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{range}\NormalTok{(auto}\SpecialCharTok{$}\NormalTok{mpg)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1]  9.0 46.6
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{range}\NormalTok{(auto}\SpecialCharTok{$}\NormalTok{cylinders)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3 8
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{range}\NormalTok{(auto}\SpecialCharTok{$}\NormalTok{displacement)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1]  68 455
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{range}\NormalTok{(auto}\SpecialCharTok{$}\NormalTok{weight)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1613 5140
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{range}\NormalTok{(auto}\SpecialCharTok{$}\NormalTok{acceleration)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1]  8.0 24.8
\end{verbatim}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(auto}\SpecialCharTok{$}\NormalTok{mpg)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 23.51587
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sd}\NormalTok{(auto}\SpecialCharTok{$}\NormalTok{mpg)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 7.825804
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(auto}\SpecialCharTok{$}\NormalTok{cylinders)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 5.458438
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sd}\NormalTok{(auto}\SpecialCharTok{$}\NormalTok{cylinders)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.701577
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(auto}\SpecialCharTok{$}\NormalTok{displacement)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 193.5327
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sd}\NormalTok{(auto}\SpecialCharTok{$}\NormalTok{displacement)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 104.3796
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(auto}\SpecialCharTok{$}\NormalTok{weight)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2970.262
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sd}\NormalTok{(auto}\SpecialCharTok{$}\NormalTok{weight)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 847.9041
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(auto}\SpecialCharTok{$}\NormalTok{acceleration)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 15.55567
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sd}\NormalTok{(auto}\SpecialCharTok{$}\NormalTok{acceleration)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2.749995
\end{verbatim}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{3}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{auto\_sub }\OtherTok{\textless{}{-}}\NormalTok{ auto[}\SpecialCharTok{{-}}\NormalTok{(}\DecValTok{10}\SpecialCharTok{:}\DecValTok{85}\NormalTok{), ]}
\FunctionTok{range}\NormalTok{(auto\_sub}\SpecialCharTok{$}\NormalTok{mpg)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 11.0 46.6
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(auto\_sub}\SpecialCharTok{$}\NormalTok{mpg)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 24.43863
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sd}\NormalTok{(auto\_sub}\SpecialCharTok{$}\NormalTok{mpg)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 7.908184
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{range}\NormalTok{(auto\_sub}\SpecialCharTok{$}\NormalTok{cylinders)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3 8
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(auto\_sub}\SpecialCharTok{$}\NormalTok{cylinders)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 5.370717
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sd}\NormalTok{(auto\_sub}\SpecialCharTok{$}\NormalTok{cylinders)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.653486
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{range}\NormalTok{(auto\_sub}\SpecialCharTok{$}\NormalTok{displacement)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1]  68 455
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(auto\_sub}\SpecialCharTok{$}\NormalTok{displacement)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 187.0498
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sd}\NormalTok{(auto\_sub}\SpecialCharTok{$}\NormalTok{displacement)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 99.63539
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{range}\NormalTok{(auto\_sub}\SpecialCharTok{$}\NormalTok{weight)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1649 4997
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(auto\_sub}\SpecialCharTok{$}\NormalTok{weight)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2933.963
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sd}\NormalTok{(auto\_sub}\SpecialCharTok{$}\NormalTok{weight)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 810.6429
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{range}\NormalTok{(auto\_sub}\SpecialCharTok{$}\NormalTok{horsepower)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "?"  "98"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(auto\_sub}\SpecialCharTok{$}\NormalTok{horsepower)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in mean.default(auto_sub$horsepower): argument is not numeric or
## logical: returning NA
\end{verbatim}

\begin{verbatim}
## [1] NA
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sd}\NormalTok{(auto\_sub}\SpecialCharTok{$}\NormalTok{horsepower)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in var(if (is.vector(x) || is.factor(x)) x else as.double(x), na.rm =
## na.rm): NAs introducidos por coerción
\end{verbatim}

\begin{verbatim}
## [1] NA
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{range}\NormalTok{(auto\_sub}\SpecialCharTok{$}\NormalTok{acceleration)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1]  8.5 24.8
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(auto\_sub}\SpecialCharTok{$}\NormalTok{acceleration)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 15.72305
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sd}\NormalTok{(auto\_sub}\SpecialCharTok{$}\NormalTok{acceleration)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2.680514
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{range}\NormalTok{(auto\_sub}\SpecialCharTok{$}\NormalTok{year)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 70 82
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(auto\_sub}\SpecialCharTok{$}\NormalTok{year)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 77.15265
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sd}\NormalTok{(auto\_sub}\SpecialCharTok{$}\NormalTok{year)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3.11123
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{range}\NormalTok{(auto\_sub}\SpecialCharTok{$}\NormalTok{origin)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1 3
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(auto\_sub}\SpecialCharTok{$}\NormalTok{origin)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.598131
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sd}\NormalTok{(auto\_sub}\SpecialCharTok{$}\NormalTok{origin)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.8161627
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{range}\NormalTok{(auto\_sub}\SpecialCharTok{$}\NormalTok{name)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "amc ambassador brougham" "vw rabbit custom"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(auto\_sub}\SpecialCharTok{$}\NormalTok{name)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in mean.default(auto_sub$name): argument is not numeric or logical:
## returning NA
\end{verbatim}

\begin{verbatim}
## [1] NA
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sd}\NormalTok{(auto\_sub}\SpecialCharTok{$}\NormalTok{name)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in var(if (is.vector(x) || is.factor(x)) x else as.double(x), na.rm =
## na.rm): NAs introducidos por coerción
\end{verbatim}

\begin{verbatim}
## [1] NA
\end{verbatim}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{4}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{auto}\SpecialCharTok{$}\NormalTok{horsepower }\OtherTok{\textless{}{-}} \FunctionTok{as.numeric}\NormalTok{(auto}\SpecialCharTok{$}\NormalTok{horsepower)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: NAs introducidos por coerción
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{pairs}\NormalTok{(auto[,}\DecValTok{1}\SpecialCharTok{:}\DecValTok{8}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\includegraphics{Econ473_ProblemSet1_PartII_files/figure-latex/unnamed-chunk-13-1.pdf}

``miles per gallon'' seems to have an inverse relationship with
``displacement'', ``horsepower'', and ``weight''. However, it seems to
have a converse relationship with ``acceleration'' and ``year''.

``displacement'' has an inverse relationship with ``acceleration'', but
a converse relationship with ``horsepower'' and ``weight''.

``horsepower'' has an inverse relationship with ``acceleration'', but a
converse relationship with ``weight''.

``acceleration'' and ``weight'' seem to have somewhat of an inverse
relationship.

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{5}
\tightlist
\item
  Yes. The plotting suggests that ``displacement'', ``horsepower'',
  ``weight'', ``acceleration'', and ``year'' could be useful when
  prediction gas mileage. Larger engines with higher horsepower have
  lower gas mileage as they tend to consumer fuel. Heavier cars also
  tend to have lower fuel efficiency. Newer cars might have improvements
  in fuel efficiency.
\end{enumerate}

Exercise 10

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{boston }\OtherTok{=} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"C:/Users/mateo/OneDrive {-} University of North Carolina at Chapel Hill/Courses/Spring 2025/Econ 573/Boston.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{dim}\NormalTok{(boston)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 506  14
\end{verbatim}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{pairs}\NormalTok{(boston)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Econ473_ProblemSet1_PartII_files/figure-latex/unnamed-chunk-16-1.pdf}

Both the proportion of non-retail business acres per town and the
nitrogen oxides concentration seem inversely related to the weighted
mean of distances to five Boston employment centres. However, the later
might not be relevant.

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cor}\NormalTok{(boston}\SpecialCharTok{$}\NormalTok{crim, boston)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##              X crim         zn     indus        chas       nox         rm
## [1,] 0.4074072    1 -0.2004692 0.4065834 -0.05589158 0.4209717 -0.2192467
##            age        dis       rad       tax   ptratio     lstat       medv
## [1,] 0.3527343 -0.3796701 0.6255051 0.5827643 0.2899456 0.4556215 -0.3883046
\end{verbatim}

The per capital crime rate seems to have a relevant positive correlation
with property tax values(tax), the lower status of the
population(lstat), and the nitrogen oxides concentration(nox), and the
proportion of non-retail business acres per town(indus). While it also
appears to have a weaker negative correlation with the mean of distances
to five Boston employment centres (dis) and the median value of
owner-occupied homes (medv) that might turn out to be relevant.

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{3}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(boston)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        X              crim                zn             indus      
##  Min.   :  1.0   Min.   : 0.00632   Min.   :  0.00   Min.   : 0.46  
##  1st Qu.:127.2   1st Qu.: 0.08205   1st Qu.:  0.00   1st Qu.: 5.19  
##  Median :253.5   Median : 0.25651   Median :  0.00   Median : 9.69  
##  Mean   :253.5   Mean   : 3.61352   Mean   : 11.36   Mean   :11.14  
##  3rd Qu.:379.8   3rd Qu.: 3.67708   3rd Qu.: 12.50   3rd Qu.:18.10  
##  Max.   :506.0   Max.   :88.97620   Max.   :100.00   Max.   :27.74  
##       chas              nox               rm             age        
##  Min.   :0.00000   Min.   :0.3850   Min.   :3.561   Min.   :  2.90  
##  1st Qu.:0.00000   1st Qu.:0.4490   1st Qu.:5.886   1st Qu.: 45.02  
##  Median :0.00000   Median :0.5380   Median :6.208   Median : 77.50  
##  Mean   :0.06917   Mean   :0.5547   Mean   :6.285   Mean   : 68.57  
##  3rd Qu.:0.00000   3rd Qu.:0.6240   3rd Qu.:6.623   3rd Qu.: 94.08  
##  Max.   :1.00000   Max.   :0.8710   Max.   :8.780   Max.   :100.00  
##       dis              rad              tax           ptratio     
##  Min.   : 1.130   Min.   : 1.000   Min.   :187.0   Min.   :12.60  
##  1st Qu.: 2.100   1st Qu.: 4.000   1st Qu.:279.0   1st Qu.:17.40  
##  Median : 3.207   Median : 5.000   Median :330.0   Median :19.05  
##  Mean   : 3.795   Mean   : 9.549   Mean   :408.2   Mean   :18.46  
##  3rd Qu.: 5.188   3rd Qu.:24.000   3rd Qu.:666.0   3rd Qu.:20.20  
##  Max.   :12.127   Max.   :24.000   Max.   :711.0   Max.   :22.00  
##      lstat            medv      
##  Min.   : 1.73   Min.   : 5.00  
##  1st Qu.: 6.95   1st Qu.:17.02  
##  Median :11.36   Median :21.20  
##  Mean   :12.65   Mean   :22.53  
##  3rd Qu.:16.95   3rd Qu.:25.00  
##  Max.   :37.97   Max.   :50.00
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{boxplot}\NormalTok{(boston}\SpecialCharTok{$}\NormalTok{crim, }\AttributeTok{main=}\StringTok{"Crime Rate"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Econ473_ProblemSet1_PartII_files/figure-latex/unnamed-chunk-18-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{boxplot}\NormalTok{(boston}\SpecialCharTok{$}\NormalTok{tax, }\AttributeTok{main=}\StringTok{"Tax Rate"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Econ473_ProblemSet1_PartII_files/figure-latex/unnamed-chunk-18-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{boxplot}\NormalTok{(boston}\SpecialCharTok{$}\NormalTok{ptratio, }\AttributeTok{main=}\StringTok{"Pupil{-}Teacher Ratio"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Econ473_ProblemSet1_PartII_files/figure-latex/unnamed-chunk-18-3.pdf}

The data for crime rates shows that the majority of the data clusters at
the bottom, such that most census tracts have lower crime rates. We
observe that the mean is 3.61352 and the maximum is 88.9762. The 3rd
quantile representing only represents up to 3.67708. There is a few
outliers with particularly high crime rates.

For tax rates, the range is from 187 to 711, with the mean being 408.2,
which maintains that the distribution is semi-uniform.

For pupil-teacher ratios tha range is from 12.60 to 22, with the mean
being 18.46. It seems as it is somewhat skewed towards higher values.

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{4}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{(boston}\SpecialCharTok{$}\NormalTok{chas }\SpecialCharTok{==} \DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 35
\end{verbatim}

35 census tracts in the data set bound the Charles Rivers.

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{5}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{median}\NormalTok{(boston}\SpecialCharTok{$}\NormalTok{ptratio)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 19.05
\end{verbatim}

The median pupil-teacher ration is 19.05

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{6}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lowest\_medv\_index }\OtherTok{\textless{}{-}} \FunctionTok{which.min}\NormalTok{(boston}\SpecialCharTok{$}\NormalTok{medv)}
\NormalTok{lowest\_medv\_index }\OtherTok{\textless{}{-}}\NormalTok{ boston[lowest\_medv\_index, ]}
\NormalTok{lowest\_medv\_index}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       X    crim zn indus chas   nox    rm age    dis rad tax ptratio lstat medv
## 399 399 38.3518  0  18.1    0 0.693 5.453 100 1.4896  24 666    20.2 30.59    5
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{range}\NormalTok{(boston}\SpecialCharTok{$}\NormalTok{crim)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1]  0.00632 88.97620
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{range}\NormalTok{(boston}\SpecialCharTok{$}\NormalTok{zn)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1]   0 100
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{range}\NormalTok{(boston}\SpecialCharTok{$}\NormalTok{indus)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1]  0.46 27.74
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{range}\NormalTok{(boston}\SpecialCharTok{$}\NormalTok{chas)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0 1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{range}\NormalTok{(boston}\SpecialCharTok{$}\NormalTok{nox)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.385 0.871
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{range}\NormalTok{(boston}\SpecialCharTok{$}\NormalTok{rm)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3.561 8.780
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{range}\NormalTok{(boston}\SpecialCharTok{$}\NormalTok{age)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1]   2.9 100.0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{range}\NormalTok{(boston}\SpecialCharTok{$}\NormalTok{dis)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1]  1.1296 12.1265
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{range}\NormalTok{(boston}\SpecialCharTok{$}\NormalTok{rad)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1]  1 24
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{range}\NormalTok{(boston}\SpecialCharTok{$}\NormalTok{tax)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 187 711
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{range}\NormalTok{(boston}\SpecialCharTok{$}\NormalTok{ptratio)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 12.6 22.0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{range}\NormalTok{(boston}\SpecialCharTok{$}\NormalTok{lstat)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1]  1.73 37.97
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(boston)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        X              crim                zn             indus      
##  Min.   :  1.0   Min.   : 0.00632   Min.   :  0.00   Min.   : 0.46  
##  1st Qu.:127.2   1st Qu.: 0.08205   1st Qu.:  0.00   1st Qu.: 5.19  
##  Median :253.5   Median : 0.25651   Median :  0.00   Median : 9.69  
##  Mean   :253.5   Mean   : 3.61352   Mean   : 11.36   Mean   :11.14  
##  3rd Qu.:379.8   3rd Qu.: 3.67708   3rd Qu.: 12.50   3rd Qu.:18.10  
##  Max.   :506.0   Max.   :88.97620   Max.   :100.00   Max.   :27.74  
##       chas              nox               rm             age        
##  Min.   :0.00000   Min.   :0.3850   Min.   :3.561   Min.   :  2.90  
##  1st Qu.:0.00000   1st Qu.:0.4490   1st Qu.:5.886   1st Qu.: 45.02  
##  Median :0.00000   Median :0.5380   Median :6.208   Median : 77.50  
##  Mean   :0.06917   Mean   :0.5547   Mean   :6.285   Mean   : 68.57  
##  3rd Qu.:0.00000   3rd Qu.:0.6240   3rd Qu.:6.623   3rd Qu.: 94.08  
##  Max.   :1.00000   Max.   :0.8710   Max.   :8.780   Max.   :100.00  
##       dis              rad              tax           ptratio     
##  Min.   : 1.130   Min.   : 1.000   Min.   :187.0   Min.   :12.60  
##  1st Qu.: 2.100   1st Qu.: 4.000   1st Qu.:279.0   1st Qu.:17.40  
##  Median : 3.207   Median : 5.000   Median :330.0   Median :19.05  
##  Mean   : 3.795   Mean   : 9.549   Mean   :408.2   Mean   :18.46  
##  3rd Qu.: 5.188   3rd Qu.:24.000   3rd Qu.:666.0   3rd Qu.:20.20  
##  Max.   :12.127   Max.   :24.000   Max.   :711.0   Max.   :22.00  
##      lstat            medv      
##  Min.   : 1.73   Min.   : 5.00  
##  1st Qu.: 6.95   1st Qu.:17.02  
##  Median :11.36   Median :21.20  
##  Mean   :12.65   Mean   :22.53  
##  3rd Qu.:16.95   3rd Qu.:25.00  
##  Max.   :37.97   Max.   :50.00
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(boston}\SpecialCharTok{$}\NormalTok{lstat)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    1.73    6.95   11.36   12.65   16.95   37.97
\end{verbatim}

The census track with lowest median value of owner-occupied homes only
has 5. In terms of crime rates, the value is way above the mean, at a
relatively higher value of 38.3518. However, not as high as the maximum
of 88.97620. In terms of zn it's at the minimum of 0. For indus its at
the start of the 3rd quintile, above the mean but below the maximum.
It's not bound by the Charles River. It's nox value is above the 3rd
quintile, but below the maximum. The rm variable is below the mean but
above the minimum. It's at the maximum age for census tracks at 100. The
dis is close to the minimum. The rad is above the minimum but below the
1st quintile. Both the tax and the ptratio are at their 3rd quintiles.
The lstat is below the 1st quintile.

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{7}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{(boston}\SpecialCharTok{$}\NormalTok{rm }\SpecialCharTok{\textgreater{}}\DecValTok{7}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 64
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{(boston}\SpecialCharTok{$}\NormalTok{rm }\SpecialCharTok{\textgreater{}}\DecValTok{8}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 13
\end{verbatim}

64 census tracts in the data set average more than seven rooms per
dwelling, while only 13 average more than eight rooms per dwelling.

\end{document}
